import { asString, asStringArray, clampTrust, normalizeId } from '@/lib/story/schema';
import type { CharacterBlueprint, HiddenPlot, Location, Npc, PlayerState, PlotThread, StoryState, TurnResolution, WorldBlueprint } from '@/lib/story/schema';

const object = (value: unknown): Record<string, unknown> | null => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null;
const list = (value: unknown) => Array.isArray(value) ? value : [];

export function storyState(value: unknown, fallback: StoryState): StoryState {
  const source = object(value); if (!source) return fallback;
  return { currentTime: asString(source.currentTime, fallback.currentTime), publicSummary: asString(source.publicSummary, fallback.publicSummary), currentSituation: asString(source.currentSituation, fallback.currentSituation), activeThreadIds: asStringArray(source.activeThreadIds, 6) || fallback.activeThreadIds };
}
export function plotThreads(value: unknown): PlotThread[] { return list(value).map(item => object(item)).filter(Boolean).map(source => ({ id: normalizeId(asString(source!.id, asString(source!.title))), title: asString(source!.title, 'Untitled thread'), status: ['active', 'dormant', 'resolved'].includes(asString(source!.status)) ? asString(source!.status) as PlotThread['status'] : 'active', publicSummary: asString(source!.publicSummary), stakes: asString(source!.stakes) })).filter(item => item.id && item.publicSummary).slice(0, 6); }
export function locations(value: unknown): Location[] { return list(value).map(item => object(item)).filter(Boolean).map(source => ({ id: normalizeId(asString(source!.id, asString(source!.name))), name: asString(source!.name, 'Unknown place'), description: asString(source!.description), atmosphere: asString(source!.atmosphere), publicState: asString(source!.publicState), connectedLocationIds: asStringArray(source!.connectedLocationIds, 8).map(normalizeId) })).filter(item => item.id && item.description).slice(0, 8); }
export function npcs(value: unknown, validLocations: string[]): Npc[] { return list(value).map(item => object(item)).filter(Boolean).map(source => ({ id: normalizeId(asString(source!.id, asString(source!.name))), name: asString(source!.name, 'Unknown'), role: asString(source!.role), appearance: asString(source!.appearance), personality: asString(source!.personality), publicFace: asString(source!.publicFace), currentObjective: asString(source!.currentObjective), currentLocationId: validLocations.includes(normalizeId(asString(source!.currentLocationId))) ? normalizeId(asString(source!.currentLocationId)) : validLocations[0] || 'unknown', status: asString(source!.status, 'active'), publicSummary: asString(source!.publicSummary) })).filter(item => item.id && item.name).slice(0, 12); }
export function hiddenPlot(value: unknown): HiddenPlot | null { const source = object(value); if (!source) return null; const result = { premise: asString(source.premise), hiddenTruth: asString(source.hiddenTruth), secrets: asStringArray(source.secrets, 12), plannedReversals: asStringArray(source.plannedReversals, 6), integritySummary: asString(source.integritySummary) }; return result.premise && result.hiddenTruth ? result : null; }

export function worldBlueprint(value: unknown): WorldBlueprint | null { const source = object(value); if (!source) return null; const locationList = locations(source.locations); const threadList = plotThreads(source.plotThreads); const hidden = hiddenPlot(source.hiddenPlot); const fallbackState: StoryState = { currentTime: 'Opening night', publicSummary: asString(source.worldSummary), currentSituation: asString(source.worldSummary), activeThreadIds: threadList.map(item => item.id) }; const state = storyState(source.storyState, fallbackState); const npcList = npcs(source.npcs, locationList.map(item => item.id)); const summary = asString(source.worldSummary); if (!summary || !hidden || locationList.length < 2 || threadList.length < 1 || npcList.length < 2) return null; return { worldSummary: summary, storyState: state, plotThreads: threadList, hiddenPlot: hidden, locations: locationList, npcs: npcList }; }

export function playerState(value: unknown, fallback: PlayerState, validLocations: string[]): PlayerState {
  const source = object(value); if (!source) return fallback; const location = normalizeId(asString(source.currentLocationId, fallback.currentLocationId));
  return { currentLocationId: validLocations.includes(location) ? location : fallback.currentLocationId, currentObjective: asString(source.currentObjective, fallback.currentObjective), currentActivity: asString(source.currentActivity, fallback.currentActivity), privateSummary: asString(source.privateSummary, fallback.privateSummary), activeQuestIds: asStringArray(source.activeQuestIds, 6), knownFacts: list(source.knownFacts).map(item => object(item)).filter(Boolean).map(item => ({ fact: asString(item!.fact), source: asString(item!.source), certainty: ['rumor', 'lead', 'confirmed'].includes(asString(item!.certainty)) ? asString(item!.certainty) as 'rumor' | 'lead' | 'confirmed' : 'lead' })).filter(item => item.fact).slice(0, 16), relationships: list(source.relationships).map(item => object(item)).filter(Boolean).map(item => ({ entityId: normalizeId(asString(item!.entityId)), label: asString(item!.label), trust: clampTrust(item!.trust), summary: asString(item!.summary) })).filter(item => item.entityId).slice(0, 16), inventory: asStringArray(source.inventory, 12), condition: asString(source.condition, fallback.condition), cliffhanger: asString(source.cliffhanger, fallback.cliffhanger), turnCount: typeof source.turnCount === 'number' && Number.isFinite(source.turnCount) ? Math.max(0, Math.floor(source.turnCount)) : fallback.turnCount };
}

export function characterBlueprint(value: unknown, fallback: PlayerState, validLocations: string[]): CharacterBlueprint | null { const source = object(value); if (!source) return null; const name = asString(source.name); const role = asString(source.role); const state = playerState(source.state, fallback, validLocations); if (!name || !role || !state.privateSummary) return null; return { name, role, appearance: asString(source.appearance), personality: asString(source.personality), background: asString(source.background), strengths: asStringArray(source.strengths, 6), constraints: asStringArray(source.constraints, 6), goals: asStringArray(source.goals, 4), privateArc: asString(source.privateArc), state }; }

export function turnResolution(value: unknown, fallbackState: PlayerState, fallbackStory: StoryState, fallbackMainContext: string, validLocations: string[]): TurnResolution | null { const source = object(value); if (!source) return null; const narration = asString(source.narration); const options = asStringArray(source.options, 4); const state = playerState(source.playerState, fallbackState, validLocations); if (!narration || options.length < 2 || !state.privateSummary) return null; return { narration, options: options.slice(0, 3), playerState: state, mainContext: asString(source.mainContext, fallbackMainContext), sceneEvent: asString(source.sceneEvent) || null, worldEvent: asString(source.worldEvent) || null, storyState: storyState(source.storyState, fallbackStory), plotThreadUpdates: plotThreads(source.plotThreadUpdates), npcUpdates: npcs(source.npcUpdates, validLocations), sceneSummary: asString(source.sceneSummary) || null }; }
